language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode8

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform Mac,iOS

script:
- xcodebuild clean build -project Cache.xcodeproj -scheme "Cache-Mac" -sdk macosx
- xcodebuild test -project Cache.xcodeproj -scheme "Cache-Mac" -sdk macosx
- xcodebuild clean build -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator
- xcodebuild test -project Cache.xcodeproj -scheme "Cache-iOS" -sdk iphonesimulator
